-- liquibase formatted sql

-- changeset jordi:1722044266071-1
CREATE TABLE comments
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content          VARCHAR(255),
    author           BIGINT,
    post             BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

-- changeset jordi:1722044266071-2
CREATE TABLE posts
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    content          TEXT,
    author           BIGINT,
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    title            VARCHAR(100)                            NOT NULL,
    CONSTRAINT pk_posts PRIMARY KEY (id)
);

-- changeset jordi:1722044266071-3
CREATE TABLE users
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    birthday         date,
    biography        VARCHAR(255),
    remember_token   VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    username         VARCHAR(40)                             NOT NULL,
    password         VARCHAR(60)                             NOT NULL,
    first_name       VARCHAR(50)                             NOT NULL,
    last_name        VARCHAR(50)                             NOT NULL,
    email            VARCHAR(255)                            NOT NULL,
    phone            VARCHAR(25),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- changeset jordi:1722044266071-4
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author) REFERENCES users (id);

-- changeset jordi:1722044266071-5
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_POST FOREIGN KEY (post) REFERENCES posts (id);

-- changeset jordi:1722044266071-6
ALTER TABLE posts
    ADD CONSTRAINT FK_POSTS_ON_AUTHOR FOREIGN KEY (author) REFERENCES users (id);

