-- liquibase formatted sql

-- changeset jorshbg:1723425799352-1
CREATE TABLE categories
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    description      VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

-- changeset jorshbg:1723425799352-2
CREATE TABLE post_category
(
    category_id BIGINT NOT NULL,
    post_id     BIGINT NOT NULL
);

-- changeset jorshbg:1723425799352-3
CREATE TABLE post_like
(
    post_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL
);

-- changeset jorshbg:1723425799352-4
CREATE TABLE post_tag
(
    post_id BIGINT NOT NULL,
    tag_id  BIGINT NOT NULL
);

-- changeset jorshbg:1723425799352-5
CREATE TABLE tags
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name             VARCHAR(255),
    created_at       TIMESTAMP WITHOUT TIME ZONE,
    last_modified_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_tags PRIMARY KEY (id)
);

-- changeset jorshbg:1723425799352-6
ALTER TABLE comments
    ADD parent_id BIGINT;

-- changeset jorshbg:1723425799352-7
ALTER TABLE posts
    ADD sleeve VARCHAR(255);

-- changeset jorshbg:1723425799352-8
ALTER TABLE posts
    ALTER COLUMN sleeve SET NOT NULL;

-- changeset jorshbg:1723425799352-9
ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

-- changeset jorshbg:1723425799352-10
ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_PARENT FOREIGN KEY (parent_id) REFERENCES comments (id);

-- changeset jorshbg:1723425799352-11
ALTER TABLE post_category
    ADD CONSTRAINT fk_poscat_on_category FOREIGN KEY (category_id) REFERENCES categories (id);

-- changeset jorshbg:1723425799352-12
ALTER TABLE post_category
    ADD CONSTRAINT fk_poscat_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

-- changeset jorshbg:1723425799352-13
ALTER TABLE post_like
    ADD CONSTRAINT fk_post_like_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

-- changeset jorshbg:1723425799352-14
ALTER TABLE post_like
    ADD CONSTRAINT fk_post_like_on_user FOREIGN KEY (user_id) REFERENCES users (id);

-- changeset jorshbg:1723425799352-15
ALTER TABLE post_tag
    ADD CONSTRAINT fk_post_tag_on_post FOREIGN KEY (post_id) REFERENCES posts (id);

-- changeset jorshbg:1723425799352-16
ALTER TABLE post_tag
    ADD CONSTRAINT fk_post_tag_on_tag FOREIGN KEY (tag_id) REFERENCES tags (id);

