-- liquibase formatted sql

-- changeset jordi:1724004140223-1
CREATE TABLE changelogs
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    class_affected_name VARCHAR(255)                            NOT NULL,
    change_type         VARCHAR(255)                            NOT NULL,
    description         VARCHAR(255)                            NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_changelogs PRIMARY KEY (id)
);

-- changeset jordi:1724004140223-2
CREATE TABLE logs
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    message               VARCHAR(255)                            NOT NULL,
    level                 VARCHAR(255)                            NOT NULL,
    throwable_stack_trace VARCHAR(255),
    created_at            TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_logs PRIMARY KEY (id)
);

-- changeset jordi:1724004140223-3
ALTER TABLE tags
    ADD active BOOLEAN;

-- changeset jordi:1724004140223-4
ALTER TABLE changelogs
    ADD CONSTRAINT FK_CHANGELOGS_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

